name: Publish Image
on:
  create:
    tag:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Registy
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build and Publish Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/lindluni/alpine-git:${{ steps.get_version.outputs.VERSION }},ghcr.io/lindluni/alpine-git:latest
